### ISSUE TITLE
invalid inputs return exit code 0, and print to STDOUT

### ISSUE THREAD

**Issue by rpetit3** [VishnuRaghuram94/AgrVATE#1]
Very minor, but errors caught all return exit code 0 (no error). The error messages are also printed to STDOUT.
```
agrvate g
Invalid input

AgrVATE: Agr Variant Assessment & Typing Engine

VERSION: agrvate v1.0

USAGE:   agrvate <fasta file>
         <fasta_file> <path/to/agrvate_databases> #Not required if installed using Conda

FLAGS:
  -h     Print this help message
  -v     Print version

SOURCE:  https://github.com/VishnuRaghuram94/AgrVATE

echo $?
0
```

Lines affected: 
https://github.com/VishnuRaghuram94/AgrVATE/blob/main/agrvate#L34
https://github.com/VishnuRaghuram94/AgrVATE/blob/main/agrvate#L41-L72
https://github.com/VishnuRaghuram94/AgrVATE/blob/main/agrvate#L84-L88
https://github.com/VishnuRaghuram94/AgrVATE/blob/main/agrvate#L91-L95
https://github.com/VishnuRaghuram94/AgrVATE/blob/main/agrvate#L191-L200
https://github.com/VishnuRaghuram94/AgrVATE/blob/main/agrvate#L206-L225

For the exits that you think should be an error, you can change them to `exit 1`

For messages you think should go to STDERR, I think you can do something like `echo "my error message" 1>&2"`

**Comment by VishnuRaghuram94** [comment]
All errors are now directed to stderr and will have exit status 1. 
Thank you!
