### ISSUE TITLE
question about agr type argument in biorxiv paper

### ISSUE THREAD

**Issue by smb20200615** [VishnuRaghuram94/AgrVATE#12]
Is it true that agr types of every clonal complex should be the same?  I have seen this trend at the mlst level but not clonal complex level. For example, ST188 is CC1 but has gp1 (not gp3 shown in your paper).

Many thanks,

**Comment by VishnuRaghuram94** [comment]
Thank you for your question. 

From our analysis yes the trend holds at the CC level except for CC45 as noted in the paper. We did however observe based on clustering that some STs likely belong in their own CCs, for eg: PUBMLST classifies ST188 in CC1 but Staphopia classifies it as CC188 (the Staphopia metadata table used in this paper can be found here (EDITED): https://github.com/VishnuRaghuram94/AgrVATE/blob/main/Manuscript_figs/Supplementals/Staphopia_metadata_stage3.4.txt). 

The only concrete example we observed of this trend not holding was in CC45. However if you have other STs or CCs where you believe have multiple _agr_ groups please let me know and I would be happy to give you more information on them.

Thank you again

**Comment by smb20200615** [comment]
Many thanks for your answer. That makes a lot of sense. I am not able to view the shared link. Is it possible to somehow get access?

**Comment by VishnuRaghuram94** [comment]
Oh apologies, does this link work?

https://github.com/VishnuRaghuram94/AgrVATE/blob/main/Manuscript_figs/Supplementals/Staphopia_metadata_stage3.4.txt

**Comment by smb20200615** [comment]
thank you so much, it does
