### ISSUE TITLE
The result of frame shift is not consistent between output of snippy and  blast result.

### ISSUE THREAD

**Issue by Tonny-zhou** [VishnuRaghuram94/AgrVATE#14]
Thank you for this great tool to detect the mutations in agr operon!

Recently, I used this great tool for some MRSA genomes, and I found that for some strains, the position of frame shift was not consistent between the output from snippy (snps.tab) and the blast result (between the reference agr sequence  and agr operon extracted by agrvate).
 
For instance, the position of frame shift in agrC of strain A from snippy was c.487delT (p.Tyr163fs); however,  the blast result showed that the position of frame shift in agrC was c.481delT. I guess this might be caused by the repeated T base?  

Please could you explain this phenomenon?

<img width="969" alt="WX20220217-124513@2x" src="https://user-images.githubusercontent.com/36953648/154407201-8989c6fa-96ec-44fb-9c9b-13ded7997341.png">

Best regards,
Tonny_z

**Comment by VishnuRaghuram94** [comment]
Thank you Tonny, 

Yes that's exactly what it is. Blast claims the the mutation is at the first T whereas snippy (the tool used for variant calling by AgrVATE) claims the mutation is the last T. There's really no way to tell exactly which position the T was deleted in as they both could be correct. 

Vishnu
