### ISSUE TITLE
novel agr types?

### ISSUE THREAD

**Issue by smb20200615** [VishnuRaghuram94/AgrVATE#15]
Hello,

If the output of AgrVATE indicates that there are missense mutations in AgrD, does that indicate that my isolate has a novel Agr type? My understanding is that there should be no mutations in the AgrD

Many thanks for your wonderful tool,

**Comment by sskashaf** [comment]
Related to the question above, why does the sequence for gp4 not match that of this paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4847544/. Could that be the reason why above is detecting missense mutations in AgrD? Thanks in advance for your clarification.

**Comment by VishnuRaghuram94** [comment]
> Hello,
> 
> If the output of AgrVATE indicates that there are missense mutations in AgrD, does that indicate that my isolate has a novel Agr type? My understanding is that there should be no mutations in the AgrD
> 
> Many thanks for your wonderful tool,

Hi [smb20200615](https://github.com/smb20200615), 

There may be missense mutations in AgrD. However, we don't believe that necessarily means it is a novel agr type, especially if the mutation does not fall in the 8 amino-acid autoinducer peptide (AIP) region. Even still, a mutation in the AIP alone cannot be considered a new _agr_ type as there needs to be appropriate compensatory mutations in _agrB_ and _agrC_ to be able to recognize the novel AIP. We did however find that AgrVATE reports _S. argenteus_ _agr_ group-1 isolates as a novel _agr_ group, as in this case - it matches the _S. aureus_ _agr_ group-1 kmers with a low match score. We did not find any un-typeable _agr_ operons in our analysis in most cases. The exceptions are noted [here](https://github.com/VishnuRaghuram94/AgrVATE/blob/main/Manuscript_figs/Supplementals/FigS3.svg)

Does this answer your question? Please let me know if you need additional clarifications.

Thank you,
Vishnu

**Comment by VishnuRaghuram94** [comment]
> Related to the question above, why does the sequence for gp4 not match that of this paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4847544/. Could that be the reason why above is detecting missense mutations in AgrD? Thanks in advance for your clarification.

Hi [sskashaf](https://github.com/sskashaf),

If you are referring to Fig3A in [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4847544/), yes our AgrD group IV reference is different from that sequence by a single amino acid. In [our paper](https://journals.asm.org/doi/10.1128/spectrum.01334-21), we did report observing multiple AgrD alleles. But we didn't consider these alleles novel agr groups as the autoinducer peptide sequence was still one of the four known types. We believe these alternate alleles are a result of the clonal-complex/sequence-type specific allelic differences in _S. aureus_ .

Hope this helps. Please let me know if you have other questions.

Thank you,
Vishnu

**Comment by smb20200615** [comment]
That makes sense. I was wondering, did you look at whether there were a higher proportion of deactivating mutations in Agr in certain clonal complexes? I am not sure how to properly quantify that - would that be numb of nonsyn mutations relative to synon as predicted by agrVATE?

**Comment by VishnuRaghuram94** [comment]
We didn't specifically look at dN/dS ratios but that would be a good thing to check. We did however attempt to train classifiers to predict the presence of agr frame shifts based on factors such as agr group, clonal complex, host body site, and infection/colonization status (Table S2) with no promising results suggesting there may not be such associations (at least no such associations detectable by this method). Our analysis may also limited by the fact that few CCs are overrepresented in NCBI.
