### ISSUE TITLE
check for usearch before processing

### ISSUE THREAD

**Issue by rpetit3** [VishnuRaghuram94/AgrVATE#2]
The check for usearch happens after processing would have occurred

https://github.com/VishnuRaghuram94/AgrVATE/blob/main/agrvate#L188-L200

I think it would be useful to check this at the start before processing.

You could then tell give the users the commands to download like you have in the README. Instead of the `cp usearch /usr/bin` you could use the same path that agrvate is in. Somthing like:

```
...
script_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
...

echo "usearch11.0.667_i86linux32 not in path, cannot perform frameshift detection\n please download usearch11.0.667_i86linux32 from https://www.drive5.com/usearch/download.html"
echo "Example commands:"  1>&2
echo "wget usearch" 1>&2
echo "gunzip usearch" 1>&2
echo " chmod 755 usearch" 1>&2
echo cp usearch ${script_dir}/usearch11.0.667_i86linux32" 1>&2
```

**Comment by VishnuRaghuram94** [comment]
1. usearch check is done only at the point where usearch is required, which is after agr group typing. 
2. The error message if usearch is not found now has instructions for downloading and installing usearch.
3. An option for skipping it is also available now ( ```-t``` does only agr typing )
