### ISSUE TITLE
check existence of individual database files

### ISSUE THREAD

**Issue by rpetit3** [VishnuRaghuram94/AgrVATE#3]
Currently only the existence of the database directory is checked. It would be useful if each database file used is checked before any processing occurs.

Steps to repeat:
```
mkdir empty_folder
agrvate ERX204841.fna empty_folder/
cat: ERX204841-results/ERX204841-agr_gp.tab: No such file or directory
cat: ERX204841-results/ERX204841-agr_gp.tab: No such file or directory
Unable to agr type

Error: File existence/permissions problem in trying to open query file empty_folder//agrD_hmm.hmm.
HMM file empty_folder//agrD_hmm.hmm not found (nor an .h3m binary of it)

grep: ERX204841-results/ERX204841-hmm.tab: No such file or directory
Unable to find agrD
usearch11.0.667_i86linux32 not in path, cannot perform frameshift detection
 please download usearch11.0.667_i86linux32 from https://www.drive5.com/usearch/download.html
```

**Comment by VishnuRaghuram94** [comment]
Done! Individual files are now checked for and only if all the required filenames are found the process continues. 

If the contents of the files themselves are modified the process will still run however the output might be affected. Will eventually come up with a way to handle this
