### ISSUE TITLE
thoughts on adding column headers to tabbed outputs?

### ISSUE THREAD

**Issue by rpetit3** [VishnuRaghuram94/AgrVATE#6]
What do you think about adding the column names to the tabbed outputs? I think it would be useful to users.

Something like:
```
cat ERX204841-results/ERX204841-summary.tab
ERX204841       gp1     13      1       s       0

cat ERX204841-results/ERX204841-summary.tab
filename	agr_group	match_score	canonical_agr	groups_found	frameshifts
ERX204841       gp1     13      1       s       0
```

**Comment by VishnuRaghuram94** [comment]
The ```-summary.tab``` and ```agr_operon_frameshifts.tab``` files now have headers. The example command for consolidating summary files from multiple runs has now been updated to include the headers.
